[2024-10-20T19:00:56.938-0300] {processor.py:186} INFO - Started process (PID=298967) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:00:56.939-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:00:56.942-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:00:56.941-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:00:56.966-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:00:56.962-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:00:56.967-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:00:56.966-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:00:56.967-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:00:56.978-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-10-20T19:03:00.570-0300] {processor.py:186} INFO - Started process (PID=300058) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:03:00.571-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:03:00.573-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:03:00.573-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:03:00.589-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:03:00.586-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:03:00.590-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:03:00.590-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:03:00.591-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:03:00.602-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-10-20T19:04:08.683-0300] {processor.py:186} INFO - Started process (PID=300589) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:04:08.684-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:04:08.686-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:04:08.685-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:04:08.703-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:04:08.699-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:04:08.704-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:04:08.703-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:04:08.705-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:04:08.716-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-10-20T19:05:20.819-0300] {processor.py:186} INFO - Started process (PID=301403) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:05:20.820-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:05:20.822-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:05:20.822-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:05:20.839-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:05:20.835-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:05:20.840-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:05:20.839-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:05:20.840-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:05:20.851-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2024-10-20T19:08:15.359-0300] {processor.py:186} INFO - Started process (PID=303693) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:08:15.360-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:08:15.362-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:08:15.362-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:08:15.378-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:08:15.374-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:08:15.379-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:08:15.379-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:08:15.380-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:08:15.391-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-10-20T19:09:23.275-0300] {processor.py:186} INFO - Started process (PID=304284) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:09:23.276-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:09:23.278-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:09:23.278-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:09:23.294-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:09:23.290-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:09:23.295-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:09:23.294-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:09:23.295-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:09:23.305-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:10:27.841-0300] {processor.py:186} INFO - Started process (PID=304817) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:10:27.842-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:10:27.844-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:10:27.844-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:10:27.859-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:10:27.856-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:10:27.861-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:10:27.860-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:10:27.861-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:10:27.871-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-10-20T19:11:35.636-0300] {processor.py:186} INFO - Started process (PID=305345) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:11:35.637-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:11:35.639-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:11:35.639-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:11:35.654-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:11:35.651-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:11:35.655-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:11:35.655-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:11:35.656-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:11:35.666-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:12:43.734-0300] {processor.py:186} INFO - Started process (PID=305880) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:12:43.735-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:12:43.737-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:12:43.737-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:12:43.752-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:12:43.749-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:12:43.753-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:12:43.753-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:12:43.754-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:12:43.764-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:13:46.869-0300] {processor.py:186} INFO - Started process (PID=306373) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:13:46.870-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:13:46.872-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:13:46.871-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:13:46.887-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:13:46.884-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:13:46.888-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:13:46.888-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:13:46.889-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:13:46.899-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:14:57.354-0300] {processor.py:186} INFO - Started process (PID=306951) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:14:57.355-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:14:57.357-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:14:57.356-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:14:57.372-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:14:57.369-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:14:57.373-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:14:57.373-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:14:57.374-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:14:57.384-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:16:05.249-0300] {processor.py:186} INFO - Started process (PID=307478) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:16:05.250-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:16:05.252-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:16:05.251-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:16:05.267-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:16:05.264-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:16:05.268-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:16:05.267-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:16:05.269-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:16:05.279-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-10-20T19:17:16.347-0300] {processor.py:186} INFO - Started process (PID=308034) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:17:16.348-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:17:16.350-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:17:16.349-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:17:16.365-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:17:16.362-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:17:16.366-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:17:16.366-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:17:16.367-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:17:16.377-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:18:31.080-0300] {processor.py:186} INFO - Started process (PID=308617) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:18:31.081-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:18:31.083-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:18:31.082-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:18:31.098-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:18:31.095-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:18:31.099-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:18:31.098-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:18:31.099-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:18:31.110-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-10-20T19:19:43.763-0300] {processor.py:186} INFO - Started process (PID=309184) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:19:43.764-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:19:43.766-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:19:43.766-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:19:43.782-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:19:43.778-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:19:43.783-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:19:43.782-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:19:43.783-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:19:43.793-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:20:50.583-0300] {processor.py:186} INFO - Started process (PID=309796) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:20:50.584-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:20:50.586-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:20:50.585-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:20:50.601-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:20:50.598-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:20:50.602-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:20:50.602-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:20:50.603-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:20:50.613-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:21:58.083-0300] {processor.py:186} INFO - Started process (PID=310402) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:21:58.084-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:21:58.086-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:21:58.085-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:21:58.101-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:21:58.098-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:21:58.102-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:21:58.101-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:21:58.102-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:21:58.113-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-10-20T19:23:03.723-0300] {processor.py:186} INFO - Started process (PID=310929) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:23:03.724-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:23:03.726-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:23:03.725-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:23:03.742-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:23:03.738-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:23:03.743-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:23:03.742-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:23:03.743-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:23:03.754-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-10-20T19:24:58.356-0300] {processor.py:186} INFO - Started process (PID=312472) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:24:58.357-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:24:58.360-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:24:58.359-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:24:58.376-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:24:58.372-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:24:58.377-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:24:58.376-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:24:58.377-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:24:58.388-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-10-20T19:26:38.447-0300] {processor.py:186} INFO - Started process (PID=313763) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:26:38.448-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:26:38.450-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:26:38.449-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:26:38.465-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:26:38.462-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:26:38.466-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:26:38.466-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:26:38.467-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:26:38.477-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:27:51.868-0300] {processor.py:186} INFO - Started process (PID=314623) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:27:51.869-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:27:51.871-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:27:51.870-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:27:51.888-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:27:51.884-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:27:51.889-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:27:51.888-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:27:51.890-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:27:51.901-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2024-10-20T19:28:54.909-0300] {processor.py:186} INFO - Started process (PID=315364) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:28:54.910-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:28:54.912-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:28:54.912-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:28:54.928-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:28:54.925-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:28:54.929-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:28:54.929-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:28:54.930-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:28:54.940-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:30:07.923-0300] {processor.py:186} INFO - Started process (PID=316180) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:30:07.925-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:30:07.927-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:30:07.926-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:30:07.944-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:30:07.940-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:30:07.945-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:30:07.944-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:30:07.946-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:30:07.960-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-10-20T19:31:12.726-0300] {processor.py:186} INFO - Started process (PID=316688) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:31:12.727-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:31:12.730-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:31:12.729-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:31:12.748-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:31:12.744-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:31:12.749-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:31:12.748-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:31:12.750-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:31:12.762-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-10-20T19:32:23.050-0300] {processor.py:186} INFO - Started process (PID=317232) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:32:23.051-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:32:23.053-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:32:23.053-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:32:23.070-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:32:23.067-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:32:23.071-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:32:23.071-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:32:23.072-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:32:23.083-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2024-10-20T19:33:29.932-0300] {processor.py:186} INFO - Started process (PID=317877) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:33:29.933-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:33:29.935-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:33:29.934-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:33:29.950-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:33:29.947-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:33:29.951-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:33:29.950-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:33:29.951-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:33:29.962-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:34:36.999-0300] {processor.py:186} INFO - Started process (PID=318593) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:34:37.000-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:34:37.002-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:34:37.001-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:34:37.018-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:34:37.014-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:34:37.019-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:34:37.019-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:34:37.020-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:34:37.030-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-10-20T19:35:46.408-0300] {processor.py:186} INFO - Started process (PID=319246) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:35:46.409-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:35:46.411-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:35:46.410-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:35:46.426-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:35:46.423-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:35:46.427-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:35:46.426-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:35:46.427-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:35:46.438-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:36:55.707-0300] {processor.py:186} INFO - Started process (PID=319786) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:36:55.707-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:36:55.709-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:36:55.709-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:36:55.725-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:36:55.721-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:36:55.726-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:36:55.725-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:36:55.726-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:36:55.736-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:38:02.344-0300] {processor.py:186} INFO - Started process (PID=320307) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:38:02.345-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:38:02.347-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:38:02.346-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:38:02.362-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:38:02.359-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:38:02.363-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:38:02.363-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:38:02.364-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:38:02.374-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-10-20T19:39:06.583-0300] {processor.py:186} INFO - Started process (PID=320814) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:39:06.587-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:39:06.590-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:39:06.589-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:39:06.617-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:39:06.613-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:39:06.619-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:39:06.618-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:39:06.620-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:39:06.634-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-10-20T19:40:13.750-0300] {processor.py:186} INFO - Started process (PID=321581) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:40:13.751-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:40:13.753-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:40:13.752-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:40:13.768-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:40:13.765-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:40:13.769-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:40:13.769-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:40:13.770-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:40:13.780-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-10-20T19:41:22.219-0300] {processor.py:186} INFO - Started process (PID=322258) to work on /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:41:22.220-0300] {processor.py:914} INFO - Processing file /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-20T19:41:22.222-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:41:22.222-0300] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:41:22.238-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:41:22.235-0300] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-20T19:41:22.239-0300] {logging_mixin.py:190} INFO - [2024-10-20T19:41:22.239-0300] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-20T19:41:22.240-0300] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-20T19:41:22.250-0300] {processor.py:208} INFO - Processing /mnt/c/Users/Pato_/OneDrive/Documentos/ITBA/PYTHON_DATA_APP/itba/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
